---

- hosts: Gluster
  sudo: yes
  roles:
    - Gluster-storage

- hosts: Xen
  sudo: yes
  roles:
    - Xen-node

- hosts: Vital
  sudo: yes
  roles:
    - Vital-gateway

- tasks:
  include: multi_pass_ssh_key.yml

- tasks:
  include: new_relic.yml
